uploads = []
generated = []

[[outputs]]
id = "3QO0pyjdfM_3WtuCPWIOD"
uri = "file://VehicleManagementSystem.pdf"
type = "pdf"
title = "Vehicle Management System — Project Documentation"

[[outputs]]
id = "dgLpNbUgHQLafuKuV2rYM"
uri = "file://VehicleManagementSystem.tar.gz"
type = "unspecified"
title = "Vehicle Management System — Full Project Source Code"

[[outputs]]
id = "6zc0OUixBZ1xsdsTIguIT"
uri = "file://VehicleManagementSystem_OOP_Code.pdf"
type = "pdf"
title = "Vehicle Management System — OOP Code & Logic (TypeScript)"

[[outputs]]
id = "GTthaVCXFrEfdQrAhJE6R"
uri = "file://VehicleManagementSystem_Java_OOP.pdf"
type = "pdf"
title = "Vehicle Management System — Java OOP Code"
